# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/tek3/B-CPP-500-LYN-5-1-babel-martin.rougeron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/tek3/B-CPP-500-LYN-5-1-babel-martin.rougeron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/tek3/B-CPP-500-LYN-5-1-babel-martin.rougeron/CMakeFiles /home/martin/tek3/B-CPP-500-LYN-5-1-babel-martin.rougeron/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/tek3/B-CPP-500-LYN-5-1-babel-martin.rougeron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named babel_server

# Build rule for target.
babel_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 babel_server
.PHONY : babel_server

# fast build rule for target.
babel_server/fast:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/build
.PHONY : babel_server/fast

src/GUI/App.o: src/GUI/App.cpp.o

.PHONY : src/GUI/App.o

# target to build an object file
src/GUI/App.cpp.o:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/App.cpp.o
.PHONY : src/GUI/App.cpp.o

src/GUI/App.i: src/GUI/App.cpp.i

.PHONY : src/GUI/App.i

# target to preprocess a source file
src/GUI/App.cpp.i:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/App.cpp.i
.PHONY : src/GUI/App.cpp.i

src/GUI/App.s: src/GUI/App.cpp.s

.PHONY : src/GUI/App.s

# target to generate assembly for a file
src/GUI/App.cpp.s:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/App.cpp.s
.PHONY : src/GUI/App.cpp.s

src/GUI/Contact.o: src/GUI/Contact.cpp.o

.PHONY : src/GUI/Contact.o

# target to build an object file
src/GUI/Contact.cpp.o:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/Contact.cpp.o
.PHONY : src/GUI/Contact.cpp.o

src/GUI/Contact.i: src/GUI/Contact.cpp.i

.PHONY : src/GUI/Contact.i

# target to preprocess a source file
src/GUI/Contact.cpp.i:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/Contact.cpp.i
.PHONY : src/GUI/Contact.cpp.i

src/GUI/Contact.s: src/GUI/Contact.cpp.s

.PHONY : src/GUI/Contact.s

# target to generate assembly for a file
src/GUI/Contact.cpp.s:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/Contact.cpp.s
.PHONY : src/GUI/Contact.cpp.s

src/GUI/ModifyPopup.o: src/GUI/ModifyPopup.cpp.o

.PHONY : src/GUI/ModifyPopup.o

# target to build an object file
src/GUI/ModifyPopup.cpp.o:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/ModifyPopup.cpp.o
.PHONY : src/GUI/ModifyPopup.cpp.o

src/GUI/ModifyPopup.i: src/GUI/ModifyPopup.cpp.i

.PHONY : src/GUI/ModifyPopup.i

# target to preprocess a source file
src/GUI/ModifyPopup.cpp.i:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/ModifyPopup.cpp.i
.PHONY : src/GUI/ModifyPopup.cpp.i

src/GUI/ModifyPopup.s: src/GUI/ModifyPopup.cpp.s

.PHONY : src/GUI/ModifyPopup.s

# target to generate assembly for a file
src/GUI/ModifyPopup.cpp.s:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/ModifyPopup.cpp.s
.PHONY : src/GUI/ModifyPopup.cpp.s

src/GUI/UserMenu.o: src/GUI/UserMenu.cpp.o

.PHONY : src/GUI/UserMenu.o

# target to build an object file
src/GUI/UserMenu.cpp.o:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/UserMenu.cpp.o
.PHONY : src/GUI/UserMenu.cpp.o

src/GUI/UserMenu.i: src/GUI/UserMenu.cpp.i

.PHONY : src/GUI/UserMenu.i

# target to preprocess a source file
src/GUI/UserMenu.cpp.i:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/UserMenu.cpp.i
.PHONY : src/GUI/UserMenu.cpp.i

src/GUI/UserMenu.s: src/GUI/UserMenu.cpp.s

.PHONY : src/GUI/UserMenu.s

# target to generate assembly for a file
src/GUI/UserMenu.cpp.s:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/GUI/UserMenu.cpp.s
.PHONY : src/GUI/UserMenu.cpp.s

src/server/babel.o: src/server/babel.cpp.o

.PHONY : src/server/babel.o

# target to build an object file
src/server/babel.cpp.o:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/server/babel.cpp.o
.PHONY : src/server/babel.cpp.o

src/server/babel.i: src/server/babel.cpp.i

.PHONY : src/server/babel.i

# target to preprocess a source file
src/server/babel.cpp.i:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/server/babel.cpp.i
.PHONY : src/server/babel.cpp.i

src/server/babel.s: src/server/babel.cpp.s

.PHONY : src/server/babel.s

# target to generate assembly for a file
src/server/babel.cpp.s:
	$(MAKE) -f CMakeFiles/babel_server.dir/build.make CMakeFiles/babel_server.dir/src/server/babel.cpp.s
.PHONY : src/server/babel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... babel_server"
	@echo "... src/GUI/App.o"
	@echo "... src/GUI/App.i"
	@echo "... src/GUI/App.s"
	@echo "... src/GUI/Contact.o"
	@echo "... src/GUI/Contact.i"
	@echo "... src/GUI/Contact.s"
	@echo "... src/GUI/ModifyPopup.o"
	@echo "... src/GUI/ModifyPopup.i"
	@echo "... src/GUI/ModifyPopup.s"
	@echo "... src/GUI/UserMenu.o"
	@echo "... src/GUI/UserMenu.i"
	@echo "... src/GUI/UserMenu.s"
	@echo "... src/server/babel.o"
	@echo "... src/server/babel.i"
	@echo "... src/server/babel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

