name: C/C++ CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get libs
      run: apt-get install conan
    - name: compile
      run: ./RUN.sh
    - name: run
      run: ./RUN.sh server
